spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: lt123
    username: root
    url: jdbc:mysql://121.41.17.185:3306/pc-admin?useSSL=false&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull

server:
  port: 9001
  servlet:
    context-path: /system

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
